### ISSUE TITLE
[REQ] Bouncing Cat Theme

### ISSUE THREAD

**Issue by 0x10F** [n4n0GH/0xchan-frontend#39]
Hello yes, I would like a blue bouncing cat theme thanks.

**Comment by n4n0GH** [comment]
On the topic of themes: you can either write your own style into the custom style field on the site, or add a new CSS file to the `0xchan-frontend/src/assets/css` directory and then add the name of the file to `0xchan-frontend/src/views/Settings.vue` at (currently) line 100-105.
